# Generated by Django 4.2 on 2024-08-15 01:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONWebhookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Processed'), (-1, 'Error')], default=0, protected=True)),
                ('source', models.GenericIPAddressField(null=True)),
                ('received', models.DateTimeField(default=django.utils.timezone.now)),
                ('headers', models.JSONField()),
                ('body', models.BinaryField()),
                ('content', models.JSONField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('received', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Processed'), (-1, 'Error')], default=0, protected=True)),
                ('webhook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_webhook.jsonwebhookdata')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ShopifyOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Processed'), (-1, 'Error')], default=0, protected=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopify_webhook.shopifyorder')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='shopifyorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'sku', 'email'), name='unique_shopify_order_sku_email'),
        ),
    ]
